server:
  port: 8060

spring:
  application:
      name: notification
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9094}
    consumer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.gilberto009199.microservices.*"
