server:
  port: 8060

spring:
  application:
      name: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: notification
    password: notification_password
    virtual-host: /
