services:
  postgresql:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: microservices_user
      POSTGRES_PASSWORD: microservices_password
      POSTGRES_ROOT_PASSWORD: microservices_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data