services:
  postgresql:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: microservices_user
      POSTGRES_PASSWORD: microservices_password
      POSTGRES_ROOT_PASSWORD: microservices_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  rabbitmq.local:
    image: 'bitnamilegacy/rabbitmq:latest'
    ports:
      - '5672:5672'
    environment:
      RABBITMQ_USERNAME: notification
      RABBITMQ_PASSWORD: notification_password
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
      RABBITMQ_NODE_PORT_NUMBER: 5672
      RABBITMQ_VHOST: /
    extra_hosts:
      host.docker.internal: host-gateway