services:
  postgresql:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: microservices_user
      POSTGRES_PASSWORD: microservices_password
      POSTGRES_ROOT_PASSWORD: microservices_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  kafka.local:
    image: 'bitnamilegacy/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka.local:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka.local:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    extra_hosts:
      - "host.docker.internal:host-gateway"